### ISSUE TITLE
Where's the implementation?

### ISSUE THREAD

**Issue by spektom** [open-amdocs/zusammen#3]
In addition to #1, I'd like to note that there's no default implementation provided. I'm sorry, but a bunch of meaningless interfaces, factories, stubs is simply useless.

**Comment by zoharsacks** [comment]
@spektom you are correct, sample implementation will come shortly.
Thanks for your comment

**Comment by talhalfon** [comment]
@spektom the sample implementation are up and running.
You can find them @ https://github.com/open-amdocs/zusammen/tree/master/samples

Thanks
